/* -------------------------------------------------------------------------
//  File Name   :   ApiKeyword.h
//  Author      :   Zhang Fan
//  Create Time :   2012-3-23 16:25:24
//  Description :
//
// -----------------------------------------------------------------------*/

#ifndef __APIKEYWORD_H__
#define __APIKEYWORD_H__

//-------------------------------------------------------------------------

// Web Api Keyword
#define KW_USER						    "user"
#define KW_USERNAME					    "userName"
#define KW_USERNAMES					"userNames"
#define KW_DESTPATH					    "destPath"
#define KW_OVERRIDE					    "override"
#define KW_PASSWORD					    "password"
#define KW_DEVICE_ID					"deviceId"
#define KW_PLR_VALUE					"plrValue"
#define KW_CLIENT_TYPE					"clientType"
#define KW_RET_URL						"returnUR"
#define KW_CLIENT_NAME					"clientName"
#define KW_CLIENT_VERSION				"clientVersion"
#define KW_TOKEN						"token"
#define KW_KEY							"key"
#define KW_GLOBALVER					"globalVersion"
#define KW_FILE_KEY					    "fileKey"
#define KW_USER_ID						"userId"
#define KW_NICK_NAME					"nickName"
#define KW_MOBILE                       "mobile"
#define KW_EMAIL						"email"
#define KW_EMAILSTATUS					"emailStatus"
#define KW_NEWEMAIL					    "newEmail"
#define KW_PASSPORT					    "passport"
#define KW_TOTAL						"total"
#define KW_USED						    "used"
#define KW_OP_VERSION					"opVer"
#define KW_SHAREINFO					"shareinfo"
#define KW_SHARE_VERSION				"shareVer"
#define KW_FILE_ID						"fileId"
#define KW_OLID                         "olid"
#define KW_PICKUP_CODE                  "pickupCode"
#define KW_EXPIREDDAY					"expiredDay"
#define KW_PREVILEGESVALUE				"previlegesValue"
#define KW_TO_RECYCEL					"toRecycel"
#define KW_PARENT_ID					"parentId"
#define KW_ROOT_ID						"rootId"
#define KW_FOLDERS						"folders"
#define KW_FILES						"files"
#define KW_NAME						    "name"
#define KW_TREE_OPVER					"treeOpVer"
#define KW_ADDR						    "addr"
#define KW_OHASH2						"ohash2"
#define KW_HASH						    "hash"
#define KW_ID							"id"
#define KW_KEY							"key"
#define KW_STUB						    "stub"
#define KW_URL							"url"
#define KW_URL2						    "speedUpUfaURLs"
#define KW_SHA1						    "sha1"
#define KW_MD5                          "md5"
#define KW_STORE_ID                     "stoid"
#define KW_NODE_URLS                    "node_urls"
#define KW_URLS                         "urls"
#define KW_SECURE_KEY                   "secure_key"
#define KW_FILE_META                    "file_meta"
#define KW_BLOCK_METAS                  "block_metas"
#define KW_BLOCKS                       "blocks"
#define KW_IS_EXISTED                   "is_existed"
#define KW_BLOCK_META                   "block_meta"
#define KW_COMMIT_META                  "commit_meta"
#define KW_ORIGIN_SHA1					"originSha1"
#define KW_COMPRESS_SHA1				"compressSha1"
#define KW_UPLOAD_SHA1					"uploadSha1"
#define KW_SIZE						    "size"
#define KW_BLOCK_INFOS                  "block_infos"
#define KW_COMMIT_METAS                 "commit_metas"
#define KW_INDEX						"index"
#define KW_COMPRESS_SIZE				"compressSize"
#define KW_UPLOAD_SIZE					"uploadSize"
#define KW_FILE_NAME					"fileName"
#define KW_FILE						    "file"
#define KW_FOLDER						"folder"
#define KW_DELETED						"deleted"
#define KW_EXITSHARE					"exited"
#define KW_TYPE						    "type"
#define KW_FILE_VER					    "fileVer"
#define KW_SHARERS						"sharers"
#define KW_SHARER						"sharer"
#define KW_MSG							"msg"
#define KW_WRITABLE					    "writable"
#define KW_SENDMAIL					    "sendMail"
#define KW_MAILCONTENT					"mailContent"
#define KW_TRUE						    "true"
#define KW_FALSE						"false"
#define KW_TO_ME						"toMe"
#define KW_OUT							"out"
#define KW_UID							"uid"
#define KW_RIGHT						"right"
#define KW_WRITE						"write"
#define KW_PRE_VER						"bakVer"
#define KW_MODTIME						"modTime"
#define KW_PROP_KEY					    "key"
#define KW_PROP_VALUE					"value"
#define KW_PATH						    "path"
#define KW_COMMAND						"command"
#define KW_CHANNEL						"channel"
#define KW_SOP_VERSION					"sopVer"	
#define KW_SHARE_ID					    "shareId"
#define KW_RESULT						"result"
#define KW_STAT                         "stat"
#define KW_JSON_DATA                    "__data__"
#define KW_RULE						    "rule"
#define KW_COUNT						"count"
#define KW_METAS						"metas"
#define KW_ADDTYPE						"addType"
#define	KW_CREATEDTIME					"createdTime"
#define KW_BLOCKINFOS					"blockInfos"
#define KW_KPXY_DEST					"kuaipan-proxy"
#define KW_FINISHED					    "finished"
#define KW_NOTSHARE					    "notshare"	
#define KW_INTERVAL						"retryInterval"

#define KW_VCODE					    "vcode"	

//--------------------------------------------------------------------------
#endif /* __APIKEYWORD_H__ */